title: Wei Hao Khoong # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  B.Sc. (Hons) Applied Mathematics 
  <br>
  National University of Singapore 
  <br><br>
  <a href="https://www.linkedin.com/in/wei-hao-khoong-6b94b1101">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.kaggle.com/khoongweihao">View My Kaggle Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
